version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 5000
    environment:
      NODE_ENV: production
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge